packages:
  device_base: !include common/device_base.yaml

esp8266:
  board: d1_mini

substitutions:
  NODE_NAME: fireplace
  FRIENDLY_NAME: Fireplace

i2c:

binary_sensor:
  - platform: analog_threshold
    name: Fan
    sensor_id: fireplace_fan_raw
    threshold: 500
    icon: mdi:weather-windy
  - platform: gpio
    name: Wall switch
    id: wall_switch
    pin:
      number: D6
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on_off: 50ms
    on_press:
      then:
        - switch.turn_on: relay
    on_release:
      then:
        - switch.turn_off: relay

switch:
  - platform: gpio
    name: Fireplace
    icon: "mdi:fireplace"
    pin:
      number: D5
      inverted: True
    id: relay
    restore_mode: ALWAYS_OFF

sensor:
  - platform: adc
    pin: A0
    id: fireplace_fan_raw
    raw: True
    update_interval: 1s
  - platform: aht10
    temperature:
      name: Temperature
      accuracy_decimals: 1
    humidity:
      name: Humidity
      accuracy_decimals: 1
    update_interval: 60s

status_led:
  pin:
    number: D4
    inverted: yes
