packages:
  device_base: !include common/device_base.yaml

substitutions:
  NODE_NAME: garage_door_controller
  DISPLAY_NAME: Garage Door Controller
  BOARD: d1_mini

# Expose Home Assistant service(s)
api:
  services:
    - service: push_button
      then:
        - switch.turn_on: relay
        - delay: 500ms
        - switch.turn_off: relay

i2c:

sensor:
  - platform: custom_aht10
    temperature:
      name: Garage Temperature
      accuracy_decimals: 1
    humidity:
      name: Garage Humidity
      accuracy_decimals: 1
    update_interval: 5min

binary_sensor:
  - platform: gpio
    device_class: garage_door
    name: Garage Door
    pin:
      number: D6
      mode: INPUT_PULLUP
    filters:
      - delayed_on_off: 250ms

switch:
  - platform: gpio
    pin:
      number: D0
      inverted: True
    id: relay
    restore_mode: ALWAYS_OFF

status_led:
  pin:
    number: D4
    inverted: yes
