packages:
  device_base: !include common/device_base.yaml


substitutions:
  NAME: garage_door_controller
  DESC: Garage Door Controller
  BOARD: d1_mini


# Expose Home Assistant service(s)
api:
  services:
    - service: push_button
      then:
        - switch.turn_on: relay
        - delay: 500ms
        - switch.turn_off: relay


i2c:


sensor:
  - platform: custom_aht10
    temperature:
      name: Garage Temperature
      accuracy_decimals: 1
    humidity:
      name: Garage Humidity
      accuracy_decimals: 1
    update_interval: 5min


text_sensor:
  - platform: two_pin_garage
    name: Garage Door
    debounce: 1s
    top_pin:
      number: D7
      inverted: True
      mode: INPUT_PULLUP
    bottom_pin:
      number: D6
      inverted: True
      mode: INPUT_PULLUP

switch:
  - platform: gpio
    pin:
      number: D0
      inverted: True
    id: relay
    restore_mode: ALWAYS_OFF


status_led:
  pin:
    number: D4
    inverted: yes