packages:
  device_base: !include common/device_base.yaml

substitutions:
  NODE_NAME: island_lights
  DISPLAY_NAME: Island Lights
  BOARD: esp01_1m

binary_sensor:
  # As of 2022-07-23 in preparation for selling the house,
  # the momentary button has been replaced with a self-latching button.
  # The Sonoff Basic can be removed and the lights can be connected
  # directly to the button
  # Button specs:
  # * SPDT self-latching
  # * 16mm thread diameter
  # * 24VDC green LED for ring illumination
  # * Switch is rated for 250VAC 3A
  - platform: gpio
    id: physical_button
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on_off: 50ms
    on_press:
      then:
        - light.turn_on: island_lights
    on_release:
      then:
        - light.turn_off: island_lights
  - platform: gpio
    id: internal_button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on_off: 50ms
    on_multi_click:
      - timing:
          - ON for at most 5s
          - OFF for at least 0.1s
        then:
          - light.toggle: island_lights
      - timing:
          - ON for at least 10s
          - OFF for at least 0.1s
        then:
          - button.press: restart_button

light:
  - platform: binary
    id: island_lights
    name: Island Lights
    output: relay

output:
  - platform: gpio
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
