packages:
  device_base: !include common/device_base.yaml

esp8266:
  board: d1_mini
  early_pin_init: false

substitutions:
  NODE_NAME: pc-power
  FRIENDLY_NAME: "PC Power"

switch:
  - platform: gpio
    id: sw1
    restore_mode: RESTORE_DEFAULT_OFF
    pin:
      number: D1
      inverted: True
  - platform: gpio
    id: sw2
    restore_mode: RESTORE_DEFAULT_OFF
    pin:
      number: D2
      inverted: True

button:
  - platform: template
    name: "PC 1 Power"
    icon: mdi:power
    on_press:
      then:
        - switch.turn_on: sw1
        - delay: 250ms
        - switch.turn_off: sw1
  - platform: template
    name: "PC 2 Power"
    icon: mdi:power
    on_press:
      then:
        - switch.turn_on: sw2
        - delay: 250ms
        - switch.turn_off: sw2

status_led:
  pin:
    number: D4
    inverted: yes
