packages:
  device_base: !include common/device_base.yaml

substitutions:
  NODE_NAME: temp_sensor_2
  DISPLAY_NAME: "Temp Sensor 2"
  BOARD: d1_mini

i2c:

sensor:
  - platform: custom_aht10
    temperature:
      name: Office Temperature
      accuracy_decimals: 1
    humidity:
      name: Office Humidity
      accuracy_decimals: 1
    update_interval: 5min

status_led:
  pin:
    number: D4
    inverted: yes
