# https://www.digiblur.com/2021/03/how-to-flash-wyze-outdoor-plug-esphome.html
# https://github.com/digiblur/digiNRG_ESPHome/blob/master/WyzeOutdoorPlug/wyzeoutdoor.yaml

packages:
  device_base: !include common/device_base.yaml

substitutions:
  NODE_NAME: wyze_outdoor_plug
  DISPLAY_NAME: Wyze Outdoor Plug
  PLATFORM: ESP32
  BOARD: esp-wrover-kit
  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "770"

switch:
  - platform: gpio
    name: $DISPLAY_NAME Relay 1
    icon: mdi:power-plug
    pin:
      number: GPIO15
      inverted: False
    restore_mode: ALWAYS_ON
    id: relay1
    on_turn_on:
      - light.turn_on: relay1_led
    on_turn_off:
      - light.turn_off: relay1_led
  - platform: gpio
    name: $DISPLAY_NAME Relay 2
    icon: mdi:power-plug
    pin:
      number: GPIO32
      inverted: False
    restore_mode: ALWAYS_OFF
    id: relay2
    on_turn_on:
      - light.turn_on: relay2_led
    on_turn_off:
      - light.turn_off: relay2_led

output:
  - platform: gpio
    pin: GPIO19
    inverted: True
    id: relay1_led_gpio
  - platform: gpio
    pin: GPIO16
    inverted: True
    id: relay2_led_gpio

light:
  - platform: binary
    id: relay1_led
    output: relay1_led_gpio
  - platform: binary
    id: relay2_led
    output: relay2_led_gpio

sensor:
  - platform: adc
    pin: GPIO34
    name: $DISPLAY_NAME Illuminance
    icon: mdi:white-balance-sunny
    unit_of_measurement: lx
    update_interval: 10s
    attenuation: 11db
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 3.90 -> 128.0
  - platform: hlw8012
    sel_pin:
      number: GPIO25
      inverted: true
    cf_pin: GPIO27
    cf1_pin: GPIO26
    current_resistor: $current_res
    voltage_divider: $voltage_div
    change_mode_every: 3
    update_interval: 10s
    current:
      name: "$DISPLAY_NAME Amps"
      unit_of_measurement: A
      accuracy_decimals: 2
    voltage:
      name: "$DISPLAY_NAME Volts"
      unit_of_measurement: V
      accuracy_decimals: 1
    power:
      name: "$DISPLAY_NAME Watts"
      unit_of_measurement: W
      accuracy_decimals: 0
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 134 -> 58

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO18
      mode: INPUT_PULLDOWN
      inverted: True
    name: $DISPLAY_NAME Button 1
    on_press:
      - switch.toggle: relay1
  - platform: gpio
    internal: true
    pin:
      number: GPIO17
      mode: INPUT_PULLDOWN
      inverted: True
    name: $DISPLAY_NAME Button 2
    on_press:
      - switch.toggle: relay2

status_led:
  pin:
    number: GPIO5
    inverted: true
