packages:
    device_base: !include common/device_base.yaml

esp8266:
    board: d1_mini

substitutions:
    NODE_NAME: temp-sensor-2
    FRIENDLY_NAME: "Temp Sensor 2"

i2c:

sensor:
    - platform: aht10
      temperature:
          name: Temperature
          accuracy_decimals: 1
      humidity:
          name: Humidity
          accuracy_decimals: 1
      update_interval: 60s

status_led:
    pin:
        number: D4
        inverted: yes
