# Based loosely on https://github.com/ratgdo/esphome-ratgdo/blob/main/static/v2board_esp8266_d1_mini.yaml

packages:
  device_base: !include device_base.yaml
  remote_package:
    url: https://github.com/ratgdo/esphome-ratgdo
    files: [base.yaml]
    ref: main
    refresh: 15min

esp8266:
  board: d1_mini
  restore_from_flash: true

substitutions:
  id_prefix: ratgdov2
  friendly_name: $FRIENDLY_NAME
  uart_tx_pin: D4
  uart_rx_pin: D2
  input_obst_pin: D7
  status_door_pin: D0
  status_obstruction_pin: D8
  dry_contact_open_pin: D5
  dry_contact_close_pin: D6
  dry_contact_light_pin: D3

safe_mode: !remove

ota:
  - id: !remove ${id_prefix}_ratgdo_ota_ws

binary_sensor:
  - id: !extend ${id_prefix}_motion
    disabled_by_default: true
  - id: !extend ${id_prefix}_button
    disabled_by_default: true
  - id: !extend ${id_prefix}_motor
    disabled_by_default: true
  - id: !extend ${id_prefix}_dry_contact_open
    disabled_by_default: true
  - id: !extend ${id_prefix}_dry_contact_close
    disabled_by_default: true
  - id: !extend ${id_prefix}_dry_contact_light
    disabled_by_default: true

button:
  - id: !remove ${id_prefix}_restart
  - id: !remove ${id_prefix}_safe_mode
  - id: !extend ${id_prefix}_toggle_door
    disabled_by_default: true

sensor:
  - id: !extend ${id_prefix}_openings
    state_class: measurement
    accuracy_decimals: 0
  - id: !extend ${id_prefix}_paired_devices_total
    state_class: measurement
    accuracy_decimals: 0

text_sensor:
  - id: !remove ${id_prefix}_firmware_version
